fixing yaml files

diff --git a/.github/workflows/additional_files.yml b/.github/workflows/additional_files.yml
--- a/.github/workflows/additional_files.yml
+++ b/.github/workflows/additional_files.yml
@@ -1,6 +1,6 @@
-name: 'additional_files'
+name: "additional_files"
 
-on: 
+on:
   push:
     branches:
       - "master"
@@ -20,28 +20,28 @@ jobs:
           - ubuntu-latest
           - macos-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Run ShellCheck
-      uses: ./
-      id: check
-      with:
-        additional_files: run finish discovery
-        ignore_paths: ignore
-        scandir: testfiles
+      - name: Run ShellCheck
+        uses: ./
+        id: check
+        with:
+          additional_files: run finish discovery
+          ignore_paths: ignore
+          scandir: testfiles
 
-    - name: Verify check
-      run: | 
-        expect="testfiles/scandir/run"
+      - name: Verify check
+        run: |
+          expect="testfiles/scandir/run"
 
-        if [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/run ]];then
-          echo "::error:: Expected file testfiles/scandir/run not found in ${{ steps.check.outputs.files }}"
-          exit 1
-        elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/finish ]];then
-          echo "::error:: Expected file testfiles/scandir/finish not found in ${{ steps.check.outputs.files }}"
-          exit 1
-        elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/discovery ]];then
-          echo "::error:: Expected file testfiles/scandir/discovery not found in ${{ steps.check.outputs.files }}"
-          exit 1
-        fi 
+          if [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/run ]];then
+            echo "::error:: Expected file testfiles/scandir/run not found in ${{ steps.check.outputs.files }}"
+            exit 1
+          elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/finish ]];then
+            echo "::error:: Expected file testfiles/scandir/finish not found in ${{ steps.check.outputs.files }}"
+            exit 1
+          elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/discovery ]];then
+            echo "::error:: Expected file testfiles/scandir/discovery not found in ${{ steps.check.outputs.files }}"
+            exit 1
+          fi
diff --git a/.github/workflows/ignore_names.yml b/.github/workflows/ignore_names.yml
--- a/.github/workflows/ignore_names.yml
+++ b/.github/workflows/ignore_names.yml
@@ -1,6 +1,6 @@
-name: 'ignore_names'
+name: "ignore_names"
 
-on: 
+on:
   push:
     branches:
       - "master"
@@ -20,25 +20,25 @@ jobs:
           - ubuntu-latest
           - macos-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Run ShellCheck
-      uses: ./
-      id: check
-      with:
-        ignore_paths: ignore
-        ignore_names: ignore_single_file.sh
+      - name: Run ShellCheck
+        uses: ./
+        id: check
+        with:
+          ignore_paths: ignore
+          ignore_names: ignore_single_file.sh
 
-    - name: Verify check
-      run: | 
-        expect="testfiles/test.bash"
-        notexpect="testfiles/ignore_single_file.sh"
+      - name: Verify check
+        run: |
+          expect="testfiles/test.bash"
+          notexpect="testfiles/ignore_single_file.sh"
 
-        if [[ ! "${{ steps.check.outputs.files }}" =~ $expect ]];then
-          echo "::error:: Expected file $expect not found in ${{ steps.check.outputs.files }}"
-          exit 1
-        elif [[ "${{ steps.check.outputs.files }}" =~ $notexpect ]];then
-          echo "::error:: Expected file $notexpect found in ${{ steps.check.outputs.files }}"
-          exit 1
-        fi 
+          if [[ ! "${{ steps.check.outputs.files }}" =~ $expect ]];then
+            echo "::error:: Expected file $expect not found in ${{ steps.check.outputs.files }}"
+            exit 1
+          elif [[ "${{ steps.check.outputs.files }}" =~ $notexpect ]];then
+            echo "::error:: Expected file $notexpect found in ${{ steps.check.outputs.files }}"
+            exit 1
+          fi
diff --git a/.github/workflows/scandir.yml b/.github/workflows/scandir.yml
--- a/.github/workflows/scandir.yml
+++ b/.github/workflows/scandir.yml
@@ -1,4 +1,4 @@
-name: 'scandir'
+name: "scandir"
 
 on:
   push:
@@ -20,44 +20,44 @@ jobs:
           - ubuntu-latest
           - macos-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v3
+      - name: Checkout
+        uses: actions/checkout@v3
 
-    - name: Run ShellCheck
-      uses: ./
-      id: one
-      with:
-        scandir: testfiles/scandir
+      - name: Run ShellCheck
+        uses: ./
+        id: one
+        with:
+          scandir: testfiles/scandir
 
-    - name: Verify check
-      run: |
-        expect="testfiles/scandir/run[[:space:]]me.bash"
-        notexpect="testfiles/test.bash"
+      - name: Verify check
+        run: |
+          expect="testfiles/scandir/run[[:space:]]me.bash"
+          notexpect="testfiles/test.bash"
 
-        if [[ ! "${{ steps.one.outputs.files }}" =~ $expect ]];then
-          echo "::error:: Expected file $expect not found in ${{ steps.one.outputs.files }}"
-          exit 1
-        elif [[ "${{ steps.one.outputs.files }}" =~ $notexpect ]];then
-          echo "::error:: Expected file $notexpect found in ${{ steps.one.outputs.files }}"
-          exit 1
-        fi
+          if [[ ! "${{ steps.one.outputs.files }}" =~ $expect ]];then
+            echo "::error:: Expected file $expect not found in ${{ steps.one.outputs.files }}"
+            exit 1
+          elif [[ "${{ steps.one.outputs.files }}" =~ $notexpect ]];then
+            echo "::error:: Expected file $notexpect found in ${{ steps.one.outputs.files }}"
+            exit 1
+          fi
 
-    - name: Run ShellCheck
-      uses: ./
-      id: two
-      with:
-        scandir: './testfiles/scandir'
-        ignore_paths: ignore
+      - name: Run ShellCheck
+        uses: ./
+        id: two
+        with:
+          scandir: "./testfiles/scandir"
+          ignore_paths: ignore
 
-    - name: Verify check
-      run: |
-        expect="testfiles/scandir/test.bash"
-        notexpect="testfiles/test.bash"
+      - name: Verify check
+        run: |
+          expect="testfiles/scandir/test.bash"
+          notexpect="testfiles/test.bash"
 
-        if [[ ! "${{ steps.two.outputs.files }}" =~ $expect ]];then
-          echo "::error:: Expected file $expect not found in ${{ steps.two.outputs.files }}"
-          exit 1
-        elif [[ "${{ steps.two.outputs.files }}" =~ $notexpect ]];then
-          echo "::error:: Expected file $notexpect found in ${{ steps.two.outputs.files }}"
-          exit 1
-        fi
+          if [[ ! "${{ steps.two.outputs.files }}" =~ $expect ]];then
+            echo "::error:: Expected file $expect not found in ${{ steps.two.outputs.files }}"
+            exit 1
+          elif [[ "${{ steps.two.outputs.files }}" =~ $notexpect ]];then
+            echo "::error:: Expected file $notexpect found in ${{ steps.two.outputs.files }}"
+            exit 1
+          fi
